version: "3.7"

services:
  nginx:
    image: nginx:1.19
    working_dir: /usr/share/nginx/html
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - symfony_demo:/home/demo
    
  phpfpm:
    build: ./php
    working_dir: /var/www/html
    volumes:
      - symfony_demo:/var/www/html
      - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

volumes:
  symfony_demo:
    external: true
